apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: python-app
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/ralphjbean-tenant/python-app/python-app@sha256:d72450563ffe42c045dc23836a1db4430c8ed96c69ab6f16b4a59e07f09ce042
        name: my-python
        resources: {}
status: {}
