apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: python-app
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/ralphjbean-tenant/python-app/python-app@sha256:de9a80911714d8971dcc71fc4bc607fc6b4ce255d616bcc3946a9f16c7681547
        name: my-python
        resources: {}
status: {}
