apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: python-app
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/ralphjbean-tenant/python-app/python-app@sha256:8208de5f99b2df6fa6b838242b08cc2cefd060d5997ac8f70d53704d8cde6f68
        name: my-python
        resources: {}
status: {}
