apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: python-app
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/ralphjbean-tenant/python-app/python-app@sha256:1a2a332c0987337e056fb0e11aa264c66afdd48333394f57addd842eec1fbbb6
        name: my-python
        resources: {}
status: {}
