apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: python-app
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: python-app
    app.kubernetes.io/part-of: python-app
  name: python-app
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: python-app
      app.kubernetes.io/instance: python-app
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: python-app
        app.kubernetes.io/instance: python-app
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/ralphjbean-tenant/python-app/python-app@sha256:de9a80911714d8971dcc71fc4bc607fc6b4ce255d616bcc3946a9f16c7681547
        name: my-python
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: 100m
            memory: 100Mi
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
