apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: python-app
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/ralphjbean-tenant/python-app/python-app@sha256:cd4c1be75114b6400aba6470022a95c983f678104fcab80f5ae109c10ca28830
        name: my-python
        resources: {}
status: {}
